import {
  Activity,
  ArrowRight,
  Award,
  Baby,
  Banknote,
  BedDouble,
  Brain,
  Building2,
  CalendarCheck,
  Camera,
  ClipboardList,
  Clock,
  Coffee,
  Compass,
  Eye,
  FileCheck,
  FileText,
  Globe,
  HandHeart,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Landmark,
  Leaf,
  LifeBuoy,
  Luggage,
  Mail,
  MapPin,
  MessageCircle,
  Microscope,
  NotebookPen,
  Phone,
  Plane,
  Receipt,
  Route,
  ScanEye,
  Search,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Sparkles,
  Stethoscope,
  Syringe,
  UserRoundCheck,
  UsersRound,
  Utensils,
  Wallet,
  Waves,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "@/types";

/**
 * Resolves the string keys stored in `/data` to real components.
 *
 * Typed as an exhaustive `Record<IconName, LucideIcon>`, so adding a name to
 * the `IconName` union without mapping it here is a compile error — which is
 * exactly the guard we want once a CMS starts supplying these values.
 */
export const iconMap: Record<IconName, LucideIcon> = {
  activity: Activity,
  "arrow-right": ArrowRight,
  award: Award,
  baby: Baby,
  banknote: Banknote,
  "bed-double": BedDouble,
  brain: Brain,
  building: Building2,
  "calendar-check": CalendarCheck,
  camera: Camera,
  "clipboard-list": ClipboardList,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  eye: Eye,
  "file-check": FileCheck,
  "file-text": FileText,
  globe: Globe,
  "hand-heart": HandHeart,
  handshake: Handshake,
  heart: Heart,
  "heart-pulse": HeartPulse,
  home: Home,
  hospital: Hospital,
  landmark: Landmark,
  leaf: Leaf,
  "life-buoy": LifeBuoy,
  luggage: Luggage,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  microscope: Microscope,
  "notebook-pen": NotebookPen,
  phone: Phone,
  plane: Plane,
  receipt: Receipt,
  route: Route,
  "scan-eye": ScanEye,
  search: Search,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  smile: Smile,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  syringe: Syringe,
  "user-round-check": UserRoundCheck,
  "users-round": UsersRound,
  utensils: Utensils,
  wallet: Wallet,
  waves: Waves,
};

export function getIcon(name: IconName): LucideIcon {
  return iconMap[name];
}
